<a href="https://colab.research.google.com/github/anastasiia-vsk/ML_course/blob/main/HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [2]:
vector = np.random.uniform(0, 1, 10)
print(vector)

[0.92579487 0.61001511 0.48884668 0.45925977 0.83869727 0.37385092
 0.94983726 0.0356796  0.71917982 0.63325153]


In [3]:
vector.shape

(10,)

In [4]:
matrix = np.array([[11, 14, 17],
                    [20, 23, 26],
                    [29, 32, 35]])
print(matrix)

[[11 14 17]
 [20 23 26]
 [29 32 35]]


In [5]:
matrix.shape

(3, 3)


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [6]:
np.round(vector + 10, 2)

array([10.93, 10.61, 10.49, 10.46, 10.84, 10.37, 10.95, 10.04, 10.72,
       10.63])

In [7]:
matrix * 2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [8]:
new_vector = vector ** 2
print(new_vector)

[0.85709613 0.37211843 0.23897108 0.21091954 0.70341311 0.13976451
 0.90219082 0.00127303 0.51721961 0.4010075 ]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [9]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [10]:
result_matrix = np.dot(B, A) # змінила порядок у множенні щоб отримати матрицю 2x2
print(result_matrix)

[[0.7281 0.5202]
 [0.2034 0.2846]]


In [11]:
result_matrix_2 = np.dot(result_matrix, C)
print(result_matrix_2)

[[0.5202]
 [0.2846]]


In [12]:
result_matrix_3 = np.dot(result_matrix, D)
print(result_matrix_3)

[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [13]:
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [14]:
vector = vector.T
vector

array([0.92579487, 0.61001511, 0.48884668, 0.45925977, 0.83869727,
       0.37385092, 0.94983726, 0.0356796 , 0.71917982, 0.63325153])

In [15]:
vector.shape
# не змінилася розмірність

(10,)

In [16]:
column_vector = np.expand_dims(vector, axis=1)
column_vector

array([[0.92579487],
       [0.61001511],
       [0.48884668],
       [0.45925977],
       [0.83869727],
       [0.37385092],
       [0.94983726],
       [0.0356796 ],
       [0.71917982],
       [0.63325153]])

In [20]:
column_vector.shape
# Після використання numpy.expand_dims і додавання нового виміру, вектор став двовимірним масивом
# expand_dims додає ось у вказаній позиції (axis=1 додає нову ось як "стовпець")

(10, 1)

In [18]:
column_vector_T = column_vector.T # операція транспонування стає "доступною"
print(column_vector_T)

[[0.92579487 0.61001511 0.48884668 0.45925977 0.83869727 0.37385092
  0.94983726 0.0356796  0.71917982 0.63325153]]


In [19]:
column_vector_T.shape

(1, 10)